POST http://localhost:8080/chat HTTP/1.1
Content-Type: application/json
Authorization: 123456

{
  "user_id": "1",
  "user_message": "Olá qual é o seu nome?"
}

###

POST http://localhost:8080/chat HTTP/1.1
Content-Type: application/json
Authorization: 123456

{
  "chat_id": "0c835849-0663-40a5-88ef-76ce811a10f0",
  "user_id": "1",
  "user_message": "Quero saber mais sobre arquitetura de softaware"
}